version: "3.9"

services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: quill_backend
    env_file: backend/.env
    environment:
      BACKEND_ENV: development
    expose:
      - "8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - public
      - private
    volumes:
      - ./backend:/app
      - ./patient_data:/patient_data

  frontend:
    build:
      context: ./frontend
    container_name: quill_frontend
    env_file: frontend/.env
    environment:
      - NODE_ENV=development
    expose:
      - "5173"
      - "5174"
    ports:
      - "5173:5173"
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: ["/bin/sh", "-c", "/app/dev-start.sh"]
    depends_on:
      - backend
    networks:
      - public

  database:
    image: postgres:16-alpine
    container_name: quill_database
    env_file: backend/.env
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
    # TODO: do we need to change quill to a env variable?
      test: ["CMD-SHELL", "pg_isready -U quill -d quill"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - private

  fhir:
    image: hapiproject/hapi:latest
    container_name: quill_fhir
    env_file: backend/.env
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/quill
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      - hapi.fhir.fhir_version=R4
      - hapi.fhir.subscription.resthook_enabled=false
      - hapi.fhir.subscription.email.enabled=false
      - hapi.fhir.subscription.websocket_enabled=false
      - hapi.fhir.cors.allowed_origin=*
    expose:
      - "8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - private
      - public
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/fhir/metadata || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  caddy:
    image: caddy:2-alpine
    container_name: quill_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/dev/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - public

volumes:
  database_data:
  caddy_data:
  caddy_config:
  frontend_node_modules:

networks:
  public: {}
  private:
    internal: true
