version: "3.9"

services:
  frontend:
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: "/api"
      # Help file watching inside Docker on macOS/Windows
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    volumes:
      - ./backend/app:/app/app
