version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quill_backend
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://quill:${POSTGRES_PASSWORD}@database:5432/quill
    expose:
      - "8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - public
      - private
    volumes:
      - ./patient_data:/patient_data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - public

  database:
    image: postgres:16-alpine
    container_name: quill_database
    environment:
      POSTGRES_USER: quill
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: quill
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quill -d quill"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - private

  caddy:
    image: caddy:2-alpine
    container_name: quill_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - public

volumes:
  database_data:
  caddy_data:
  caddy_config:
  frontend_node_modules:

networks:
  public: {}
  private:
    internal: true   
