/**
 * Public site colour palette
 *
 * Re-exports from the central theme for use in TSX components.
 * CSS modules use the matching custom properties generated by
 * cssVariablesResolver in theme.ts (e.g. var(--public-navy)).
 */
import { publicColours } from "@/theme";

export const colours = publicColours;
