#!/usr/bin/env python3
"""Write the list of email themes, from ``shared/brand.yaml``.

A theme is one brand's look for every email, and ``shared/brand.yaml``
holds one under each key of ``email_themes``. Those keys are the list of
brands an email can go out as. Two languages need that list as a type
their checkers can read, and neither checker can open a YAML file:

- ``backend/app/email/theme.py``, for mypy;
- ``frontend/src/generated/emailThemes.ts``, for TypeScript.

So both are written here, from the one file, and committed. Adding a
brand is adding its theme to ``shared/brand.yaml`` and running this.

Usage:
    just email-themes

The pre-commit hook ``generate-email-themes`` runs it whenever
``shared/brand.yaml`` is in a commit, and stages what it writes.
``tests/test_email_theme.py`` fails while ``theme.py`` is behind the
YAML, and ``emailThemes.test.ts`` does the same for the frontend's file.

**This imports nothing from the app**, on purpose. ``app.email.brand``
refuses to load when the themes in the YAML and the names in
``theme.py`` disagree, which is exactly the state this script is run to
put right. A generator that needed the app to import would be unable to
run when it was needed.
"""

import re
import sys
from pathlib import Path

import yaml

# Found from this file and not the working directory, and by the same
# depth in both places it runs: in a checkout this is
# ``<repo>/backend/scripts/``, and in a container the backend is mounted
# at ``/app`` with ``shared/`` beside it at ``/shared``. So the backend is
# one level up whatever it is called, and its neighbours two.
_BACKEND = Path(__file__).resolve().parents[1]
_ROOT = _BACKEND.parent

BRAND_YAML_PATH = _ROOT / "shared" / "brand.yaml"
PYTHON_PATH = _BACKEND / "app" / "email" / "theme.py"
TYPESCRIPT_PATH = _ROOT / "frontend" / "src" / "generated" / "emailThemes.ts"

#: What a theme may be called: it becomes a Python and a TypeScript
#: string, a folder name under ``templates/campaigns/`` and part of a
#: rendered preview's file name.
_NAME = re.compile(r"[a-z][a-z0-9_]*")


class ThemeNamesError(Exception):
    """The themes in the brand file cannot be turned into a list."""


def theme_names(brand_yaml: Path = BRAND_YAML_PATH) -> list[str]:
    """The names of the email themes, in the order the file gives them.

    Args:
        brand_yaml: The brand file, normally ``shared/brand.yaml``.

    Returns:
        The keys of ``email_themes``.

    Raises:
        ThemeNamesError: If the file has no themes, or a name is not
            lower-case letters, digits and underscores.
    """
    loaded = yaml.safe_load(brand_yaml.read_text(encoding="utf-8")) or {}
    themes = loaded.get("email_themes") if isinstance(loaded, dict) else None

    if not isinstance(themes, dict) or not themes:
        raise ThemeNamesError(f"No email_themes in {brand_yaml.name}")

    names = [str(name) for name in themes]

    for name in names:
        if not _NAME.fullmatch(name):
            raise ThemeNamesError(
                f"{name!r} is not a theme name: use lower-case letters, "
                "digits and underscores, starting with a letter"
            )

    return names


def python_source(names: list[str]) -> str:
    """The whole of ``theme.py`` for *names*.

    Each name is on a line of its own with a comma after it, which Black
    leaves alone however many there are.
    """
    literal = "".join(f'    "{name}",\n' for name in names)

    return f'''"""The brands an email can go out as, named in one place.

**Generated from ``shared/brand.yaml``. Do not edit this file.** To add
or rename a brand, change ``email_themes`` there and run
``just email-themes``, which writes this and the frontend's copy. The
pre-commit hook does it for a commit that changes the brand file.

A theme is one brand's look for every email: its colours, fonts, logo and
names, read by :mod:`app.email.brand`. This module holds only which
themes there are. It is a file of its own, written out as a ``Literal``,
because mypy must be able to read the names and cannot open a YAML file.

Nothing is imported here from the rest of the app, so any module may
import this one.
"""

from typing import Literal, get_args

#: One brand an email can go out as: a key of ``email_themes``.
EmailThemeName = Literal[
{literal}]

#: Every theme name, read from the type above. Loop over this; never
#: write the list out again.
EMAIL_THEME_NAMES: tuple[EmailThemeName, ...] = get_args(EmailThemeName)
'''


def typescript_source(names: list[str]) -> str:
    """The whole of ``emailThemes.ts`` for *names*.

    One name to a line, and marked for Prettier to leave alone, so the
    file is the same shape however many there are.
    """
    items = "".join(f'  "{name}",\n' for name in names)

    return f"""/**
 * The brands an email can go out as
 *
 * Generated from `shared/brand.yaml`. Do not edit this file. To add or
 * rename a brand, change `email_themes` there and run
 * `just email-themes`, which writes this and the backend's copy
 * (`backend/app/email/theme.py`).
 *
 * Committed, unlike the JSON beside it, because TypeScript needs the
 * names as a type and a type cannot be read out of a file made when the
 * build starts.
 */

// prettier-ignore
export const EMAIL_THEME_NAMES = [
{items}] as const;

/** One brand an email can go out as: a key of `email_themes`. */
export type EmailThemeName = (typeof EMAIL_THEME_NAMES)[number];
"""


def write(brand_yaml: Path = BRAND_YAML_PATH) -> list[Path]:
    """Write both files, and say which changed.

    Args:
        brand_yaml: The brand file to read.

    Returns:
        The files whose contents changed.
    """
    names = theme_names(brand_yaml)
    changed: list[Path] = []

    for path, source in (
        (PYTHON_PATH, python_source(names)),
        (TYPESCRIPT_PATH, typescript_source(names)),
    ):
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current == source:
            continue

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")
        changed.append(path)

    return changed


def main() -> int:
    """Write the files and report.

    Returns:
        0 when they are written, 1 when the brand file cannot be used.
    """
    try:
        names = theme_names()
        changed = write()
    except (ThemeNamesError, OSError, yaml.YAMLError) as exc:
        print(f"✗ {exc}", file=sys.stderr)

        return 1

    print(f"Email themes: {', '.join(names)}")

    if changed:
        for path in changed:
            print(f"  wrote {path}")
    else:
        print("  both files already match")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
