"""The brands an email can go out as, named in one place.

**Generated from ``shared/brand.yaml``. Do not edit this file.** To add
or rename a brand, change ``email_themes`` there and run
``just email-themes``, which writes this and the frontend's copy. The
pre-commit hook does it for a commit that changes the brand file.

A theme is one brand's look for every email: its colours, fonts, logo and
names, read by :mod:`app.email.brand`. This module holds only which
themes there are. It is a file of its own, written out as a ``Literal``,
because mypy must be able to read the names and cannot open a YAML file.

Nothing is imported here from the rest of the app, so any module may
import this one.
"""

from typing import Literal, get_args

#: One brand an email can go out as: a key of ``email_themes``.
EmailThemeName = Literal[
    "quill",
    "ldd",
]

#: Every theme name, read from the type above. Loop over this; never
#: write the list out again.
EMAIL_THEME_NAMES: tuple[EmailThemeName, ...] = get_args(EmailThemeName)
