"""Integration tests for the Alembic autogenerate-drift check.

These require a real, migrated PostgreSQL database - SQLite unit tests
build their schema from model metadata directly (see `conftest.py`) and
never exercise Alembic's autogenerate comparison. Run by the dedicated
`alembic_drift_check` CI job. No `just` recipe runs them locally:
`just ub` leaves out everything marked `integration`, and has no
Postgres to give them.
"""

from __future__ import annotations

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Column, Integer, Table

from alembic import command
from app.models import Base

pytestmark = [pytest.mark.integration, pytest.mark.migration]


@pytest.fixture
def alembic_config() -> Config:
    """Alembic config pointing at the same alembic.ini used on deploy."""
    return Config("alembic.ini")


def test_no_drift_on_migrated_head(alembic_config: Config) -> None:
    """A DB migrated to head must show no pending autogenerate changes."""
    command.check(alembic_config)


def test_unmigrated_model_change_is_detected(
    alembic_config: Config,
) -> None:
    """A model change with no matching migration must be flagged."""
    probe_table = Table(
        "_alembic_drift_check_probe",
        Base.metadata,
        Column("id", Integer, primary_key=True),
    )

    try:
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(alembic_config)
    finally:
        Base.metadata.remove(probe_table)
