"""The generated list of email themes matches ``shared/brand.yaml``.

``app/email/theme.py`` is written by ``scripts/generate_email_themes.py``
and committed, because mypy cannot read the names out of a YAML file.
This is what stops it falling behind. Run ``just email-themes`` and
commit the result when it fails.
"""

from pathlib import Path

import pytest

from app.email.brand import BRAND
from app.email.theme import EMAIL_THEME_NAMES
from scripts.generate_email_themes import (
    PYTHON_PATH,
    ThemeNamesError,
    python_source,
    theme_names,
    typescript_source,
)

_FIX = "Run `just email-themes` and commit the result."


def _brand_file(tmp_path: Path, body: str) -> Path:
    path = tmp_path / "brand.yaml"
    path.write_text(body, encoding="utf-8")

    return path


class TestTheCommittedFile:
    def test_matches_a_fresh_one(self) -> None:
        assert PYTHON_PATH.read_text(encoding="utf-8") == python_source(
            theme_names()
        ), f"backend/app/email/theme.py is out of date. {_FIX}"

    def test_names_every_theme_in_the_brand_file_and_no_other(self) -> None:
        assert list(EMAIL_THEME_NAMES) == theme_names()
        assert set(EMAIL_THEME_NAMES) == set(BRAND.email_themes)


class TestReadingTheNames:
    def test_keeps_the_order_the_file_gives(self, tmp_path: Path) -> None:
        path = _brand_file(tmp_path, "email_themes:\n  b: {}\n  a: {}\n")

        assert theme_names(path) == ["b", "a"]

    @pytest.mark.parametrize(
        "body", ["", "brand: {}\n", "email_themes: {}\n", "email_themes: []\n"]
    )
    def test_a_file_with_no_themes_is_refused(
        self, tmp_path: Path, body: str
    ) -> None:
        with pytest.raises(ThemeNamesError, match="No email_themes"):
            theme_names(_brand_file(tmp_path, body))

    @pytest.mark.parametrize(
        "name", ["Quill", "let's-do", "2nd", "with space", '"quote"']
    )
    def test_a_name_that_could_not_be_code_is_refused(
        self, tmp_path: Path, name: str
    ) -> None:
        """It becomes a string in two languages, and a folder name."""
        path = _brand_file(tmp_path, f"email_themes:\n  {name!r}: {{}}\n")

        with pytest.raises(ThemeNamesError, match="not a theme name"):
            theme_names(path)


class TestWhatIsWritten:
    def test_a_third_theme_is_one_more_line_in_each(self) -> None:
        names = ["quill", "ldd", "turva"]

        assert '    "turva",\n' in python_source(names)
        assert '  "turva",\n' in typescript_source(names)

    def test_both_say_they_are_generated(self) -> None:
        for source in (python_source(["a"]), typescript_source(["a"])):
            assert "Do not edit this file" in source
            assert "just email-themes" in source
