/**
 * Application Icon Registry
 *
 * Single source of truth for all Tabler icons used in the application.
 * Components MUST import icons from here — never directly from
 * "@tabler/icons-react". To add a new icon, import it below and add
 * it to both the re-export and the iconCatalogue object.
 *
 * The Icon stories in Storybook use iconCatalogue to display the full
 * set automatically.
 */

import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconAlertTriangle,
  IconArrowLeft,
  IconBell,
  IconBook,
  IconBuildingCommunity,
  IconCalendar,
  IconCalendarWeek,
  IconChalkboardTeacher,
  IconChartBar,
  IconCurrencyPound,
  IconCheck,
  IconChevronLeft,
  IconClock,
  IconDatabase,
  IconDots,
  IconDownload,
  IconEdit,
  IconExclamationCircle,
  IconFileText,
  IconGenderAgender,
  IconGenderFemale,
  IconGenderMale,
  IconHeartPlus,
  IconHome,
  IconHome2,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMessage,
  IconPencil,
  IconPhoneRinging,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconShieldCheck,
  IconSlice,
  IconStack2,
  IconTrash,
  IconUser,
  IconUserCheck,
  IconUserMinus,
  IconUserOff,
  IconUserPlus,
  IconX,
} from "@tabler/icons-react";

export {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconAlertTriangle,
  IconArrowLeft,
  IconBell,
  IconBook,
  IconBuildingCommunity,
  IconCalendar,
  IconCalendarWeek,
  IconChalkboardTeacher,
  IconChartBar,
  IconCurrencyPound,
  IconCheck,
  IconChevronLeft,
  IconClock,
  IconDatabase,
  IconDots,
  IconDownload,
  IconEdit,
  IconExclamationCircle,
  IconFileText,
  IconGenderAgender,
  IconGenderFemale,
  IconGenderMale,
  IconHeartPlus,
  IconHome,
  IconHome2,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMessage,
  IconPencil,
  IconPhoneRinging,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconShieldCheck,
  IconSlice,
  IconStack2,
  IconTrash,
  IconUser,
  IconUserCheck,
  IconUserMinus,
  IconUserOff,
  IconUserPlus,
  IconX,
};

/**
 * Icon catalogue — maps display names to icon components.
 * Used by Storybook to render the full icon grid automatically.
 */
export const iconCatalogue = {
  AdjustmentsHorizontal: IconAdjustmentsHorizontal,
  AlertCircle: IconAlertCircle,
  AlertCircleFilled: IconAlertCircleFilled,
  AlertTriangle: IconAlertTriangle,
  ArrowLeft: IconArrowLeft,
  Bell: IconBell,
  Book: IconBook,
  BuildingCommunity: IconBuildingCommunity,
  Calendar: IconCalendar,
  CalendarWeek: IconCalendarWeek,
  ChalkboardTeacher: IconChalkboardTeacher,
  ChartBar: IconChartBar,
  CurrencyPound: IconCurrencyPound,
  Check: IconCheck,
  ChevronLeft: IconChevronLeft,
  Clock: IconClock,
  Database: IconDatabase,
  Dots: IconDots,
  Download: IconDownload,
  Edit: IconEdit,
  ExclamationCircle: IconExclamationCircle,
  FileText: IconFileText,
  GenderAgender: IconGenderAgender,
  GenderFemale: IconGenderFemale,
  GenderMale: IconGenderMale,
  HeartPlus: IconHeartPlus,
  Home: IconHome,
  Home2: IconHome2,
  Logout: IconLogout,
  Mail: IconMail,
  Menu2: IconMenu2,
  Message: IconMessage,
  Pencil: IconPencil,
  PhoneRinging: IconPhoneRinging,
  Plus: IconPlus,
  Refresh: IconRefresh,
  Search: IconSearch,
  Settings: IconSettings,
  ShieldCheck: IconShieldCheck,
  Slice: IconSlice,
  Stack2: IconStack2,
  Trash: IconTrash,
  User: IconUser,
  UserCheck: IconUserCheck,
  UserMinus: IconUserMinus,
  UserOff: IconUserOff,
  UserPlus: IconUserPlus,
  X: IconX,
} as const;
