/**
 * Application Icon Registry
 *
 * Single source of truth for all Tabler icons used in the application.
 * Components MUST import icons from here — never directly from
 * "@tabler/icons-react". To add a new icon, import it below and add
 * it to both the re-export and the iconCatalogue object.
 *
 * The Icon stories in Storybook use iconCatalogue to display the full
 * set automatically.
 */

import {
  IconAccessible,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowsShuffle,
  IconArrowUp,
  IconArrowsSort,
  IconBadgeCc,
  IconBell,
  IconBook,
  IconBuildingCommunity,
  IconBuildingHospital,
  IconCalendar,
  IconCalendarWeek,
  IconCertificate,
  IconChalkboardTeacher,
  IconChartBar,
  IconCircleCheck,
  IconCurrencyPound,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronUp,
  IconClock,
  IconDatabase,
  IconDeviceMobile,
  IconDots,
  IconDownload,
  IconEdit,
  IconEPassport,
  IconExclamationCircle,
  IconEye,
  IconFileText,
  IconFilter2,
  IconGenderAgender,
  IconGenderFemale,
  IconGenderMale,
  IconHeartPlus,
  IconHome,
  IconHome2,
  IconInfoCircle,
  IconKeyboard,
  IconLock,
  IconLogin,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMessage,
  IconMessageReport,
  IconMoon,
  IconPencil,
  IconPhoneRinging,
  IconPhoto,
  IconPlayerPlay,
  IconPlus,
  IconPresentation,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconShieldCheck,
  IconSlice,
  IconStack2,
  IconTrash,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserMinus,
  IconUserOff,
  IconUserPlus,
  IconWifi,
  IconWifiOff,
  IconX,
} from "@tabler/icons-react";

export {
  IconAccessible,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowsShuffle,
  IconArrowUp,
  IconArrowsSort,
  IconBadgeCc,
  IconBell,
  IconBook,
  IconBuildingCommunity,
  IconBuildingHospital,
  IconCalendar,
  IconCalendarWeek,
  IconCertificate,
  IconChalkboardTeacher,
  IconChartBar,
  IconCircleCheck,
  IconCurrencyPound,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronUp,
  IconClock,
  IconDatabase,
  IconDeviceMobile,
  IconDots,
  IconDownload,
  IconEdit,
  IconEPassport,
  IconExclamationCircle,
  IconEye,
  IconFileText,
  IconFilter2,
  IconGenderAgender,
  IconGenderFemale,
  IconGenderMale,
  IconHeartPlus,
  IconHome,
  IconHome2,
  IconInfoCircle,
  IconKeyboard,
  IconLock,
  IconLogin,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMessage,
  IconMessageReport,
  IconMoon,
  IconPencil,
  IconPhoneRinging,
  IconPhoto,
  IconPlayerPlay,
  IconPlus,
  IconPresentation,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconShieldCheck,
  IconSlice,
  IconStack2,
  IconTrash,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserMinus,
  IconUserOff,
  IconUserPlus,
  IconWifi,
  IconWifiOff,
  IconX,
};

/**
 * Icon catalogue — maps display names to icon components.
 * Used by Storybook to render the full icon grid automatically.
 */
export const iconCatalogue = {
  Accessible: IconAccessible,
  AdjustmentsHorizontal: IconAdjustmentsHorizontal,
  AlertCircle: IconAlertCircle,
  AlertCircleFilled: IconAlertCircleFilled,
  AlertTriangle: IconAlertTriangle,
  ArrowDown: IconArrowDown,
  ArrowLeft: IconArrowLeft,
  ArrowsShuffle: IconArrowsShuffle,
  ArrowUp: IconArrowUp,
  ArrowsSort: IconArrowsSort,
  BadgeCc: IconBadgeCc,
  Bell: IconBell,
  Book: IconBook,
  BuildingCommunity: IconBuildingCommunity,
  BuildingHospital: IconBuildingHospital,
  Calendar: IconCalendar,
  CalendarWeek: IconCalendarWeek,
  Certificate: IconCertificate,
  ChalkboardTeacher: IconChalkboardTeacher,
  ChartBar: IconChartBar,
  CircleCheck: IconCircleCheck,
  CurrencyPound: IconCurrencyPound,
  Check: IconCheck,
  ChevronDown: IconChevronDown,
  ChevronLeft: IconChevronLeft,
  ChevronUp: IconChevronUp,
  Clock: IconClock,
  Database: IconDatabase,
  DeviceMobile: IconDeviceMobile,
  Dots: IconDots,
  Download: IconDownload,
  Edit: IconEdit,
  EPassport: IconEPassport,
  ExclamationCircle: IconExclamationCircle,
  Eye: IconEye,
  FileText: IconFileText,
  Filter2: IconFilter2,
  GenderAgender: IconGenderAgender,
  GenderFemale: IconGenderFemale,
  GenderMale: IconGenderMale,
  HeartPlus: IconHeartPlus,
  Home: IconHome,
  Home2: IconHome2,
  InfoCircle: IconInfoCircle,
  Keyboard: IconKeyboard,
  Lock: IconLock,
  Login: IconLogin,
  Logout: IconLogout,
  Mail: IconMail,
  Menu2: IconMenu2,
  Message: IconMessage,
  MessageReport: IconMessageReport,
  Moon: IconMoon,
  Pencil: IconPencil,
  PhoneRinging: IconPhoneRinging,
  Photo: IconPhoto,
  PlayerPlay: IconPlayerPlay,
  Plus: IconPlus,
  Presentation: IconPresentation,
  Refresh: IconRefresh,
  Search: IconSearch,
  Send: IconSend,
  Settings: IconSettings,
  ShieldCheck: IconShieldCheck,
  Slice: IconSlice,
  Stack2: IconStack2,
  Trash: IconTrash,
  Upload: IconUpload,
  User: IconUser,
  UserCheck: IconUserCheck,
  UserMinus: IconUserMinus,
  UserOff: IconUserOff,
  UserPlus: IconUserPlus,
  Wifi: IconWifi,
  WifiOff: IconWifiOff,
  X: IconX,
} as const;
