"""updates for mypy

Revision ID: 055bc31fb937
Revises: ce0e2ca7d2ca
Create Date: 2025-09-26 06:07:21.808622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055bc31fb937'
down_revision: Union[str, None] = 'ce0e2ca7d2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
