"""add email_verified to users

Revision ID: 197844c56085
Revises: 597b0f9d0f9d
Create Date: 2026-05-21 17:56:23.019102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "197844c56085"
down_revision: Union[str, None] = "597b0f9d0f9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    # Existing users are already verified (don't break existing accounts)
    op.execute("UPDATE users SET email_verified = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
