"""add organisation passport lead specialties

Revision ID: 79a6ba344abb
Revises: 95fdabd48221
Create Date: 2026-09-27 08:08:08.010741

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79a6ba344abb"
down_revision: str | None = "95fdabd48221"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_unit_passport_specialty",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_unit_id", sa.Integer(), nullable=False),
        sa.Column("specialty_id", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_by", sa.Integer(), nullable=True),
        sa.Column("set_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "position >= 1", name="ck_org_unit_passport_specialty_position"
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["org_unit.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["set_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_unit_id",
            "position",
            name="uq_org_unit_passport_specialty_unit_position",
        ),
        sa.UniqueConstraint(
            "org_unit_id",
            "specialty_id",
            name="uq_org_unit_passport_specialty_unit_specialty",
        ),
    )
    op.create_index(
        op.f("ix_org_unit_passport_specialty_org_unit_id"),
        "org_unit_passport_specialty",
        ["org_unit_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_org_unit_passport_specialty_org_unit_id"),
        table_name="org_unit_passport_specialty",
    )
    op.drop_table("org_unit_passport_specialty")
    # ### end Alembic commands ###
