"""Initial baseline schema.

Single squashed baseline for the core database, autogenerated from the current
models (``Base.metadata`` plus the teaching models) against an empty database.
It supersedes the entire pre-launch migration history, which was collapsed into
this one revision while there was no live data. ``downgrade()`` drops every
object created here, returning the database to ``base`` (empty).

Revision ID: 878bc9300d4f
Revises:
Create Date: 2026-08-12 19:39:56.316066

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "878bc9300d4f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "fhir_conversation_id", sa.String(length=255), nullable=False
        ),
        sa.Column("patient_id", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "include_patient_as_participant", sa.Boolean(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_fhir_conversation_id"),
        "conversations",
        ["fhir_conversation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_conversations_patient_id"),
        "conversations",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "organisations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organisations_name"), "organisations", ["name"], unique=False
    )
    op.create_table(
        "patient_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_metadata_patient_id"),
        "patient_metadata",
        ["patient_id"],
        unique=True,
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["sites.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sites_name"), "sites", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("totp_secret", sa.String(length=64), nullable=True),
        sa.Column("is_totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "token_version", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("fhir_patient_id", sa.String(length=255), nullable=True),
        sa.Column("system_permissions", sa.String(length=20), nullable=False),
        sa.Column("base_profession", sa.String(length=100), nullable=False),
        sa.Column("additional_competencies", sa.JSON(), nullable=False),
        sa.Column("removed_competencies", sa.JSON(), nullable=False),
        sa.Column("professional_registrations", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("fhir_patient_id"),
    )
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    op.create_table(
        "assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("bank_version", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("score_breakdown", sa.JSON(), nullable=True),
        sa.Column("is_passed", sa.Boolean(), nullable=True),
        sa.Column("exam_ref", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_exam_ref"),
        "assessments",
        ["exam_ref"],
        unique=True,
    )
    op.create_index(
        op.f("ix_assessments_organisation_id"),
        "assessments",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessments_question_bank_id"),
        "assessments",
        ["question_bank_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessments_user_id"),
        "assessments",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "conversation_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "user_id", name="uq_conv_participant"
        ),
    )
    op.create_index(
        op.f("ix_conversation_participants_conversation_id"),
        "conversation_participants",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_participants_user_id"),
        "conversation_participants",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "external_patient_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.String(length=255), nullable=False),
        sa.Column("granted_by_user_id", sa.Integer(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_level", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "patient_id", name="uq_external_user_patient"
        ),
    )
    op.create_index(
        op.f("ix_external_patient_access_patient_id"),
        "external_patient_access",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_patient_access_user_id"),
        "external_patient_access",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "message_organisation",
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("conversation_id", "organisation_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "fhir_communication_id", sa.String(length=255), nullable=False
        ),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("amends_id", sa.Integer(), nullable=True),
        sa.Column("redacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redacted_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["amends_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["redacted_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_fhir_communication_id"),
        "messages",
        ["fhir_communication_id"],
        unique=True,
    )
    op.create_table(
        "organisation_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("feature_key", sa.String(length=50), nullable=False),
        sa.Column("enabled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enabled_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id", "feature_key", name="uq_org_feature"
        ),
    )
    op.create_index(
        op.f("ix_organisation_features_feature_key"),
        "organisation_features",
        ["feature_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organisation_features_organisation_id"),
        "organisation_features",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "organisation_patient_member",
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.String(length=255), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("organisation_id", "patient_id"),
    )
    op.create_table(
        "organisation_site",
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("organisation_id", "site_id"),
    )
    op.create_table(
        "organisation_staff_member",
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("organisation_id", "user_id"),
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("keys_p256dh", sa.String(), nullable=False),
        sa.Column("keys_auth", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "endpoint", name="uq_push_user_endpoint"
        ),
    )
    op.create_table(
        "question_bank_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column(
            "cover_image_filename", sa.String(length=255), nullable=True
        ),
        sa.Column("cover_image_focus", sa.String(length=50), nullable=True),
        sa.Column("config_yaml", sa.JSON(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["synced_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id",
            "question_bank_id",
            "version",
            name="uq_qb_config_org_bank_ver",
        ),
    )
    op.create_index(
        op.f("ix_question_bank_configs_organisation_id"),
        "question_bank_configs",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_configs_question_bank_id"),
        "question_bank_configs",
        ["question_bank_id"],
        unique=False,
    )
    op.create_table(
        "question_bank_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("bank_version", sa.Integer(), nullable=False),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_option_id", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_bank_items_organisation_id"),
        "question_bank_items",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_items_question_bank_id"),
        "question_bank_items",
        ["question_bank_id"],
        unique=False,
    )
    op.create_table(
        "question_bank_org_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("site_registration", sa.Boolean(), nullable=False),
        sa.Column("coordinator_email", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id",
            "question_bank_id",
            name="uq_qb_org_status_org_bank",
        ),
    )
    op.create_index(
        op.f("ix_question_bank_org_status_organisation_id"),
        "question_bank_org_status",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "question_bank_syncs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("items_created", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_bank_syncs_organisation_id"),
        "question_bank_syncs",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "site_staff_member",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("site_id", "user_id"),
    )
    op.create_index(
        "ix_site_staff_one_clinical_lead",
        "site_staff_member",
        ["site_id"],
        unique=True,
        postgresql_where=sa.text("role = 'clinical_lead'"),
        sqlite_where=sa.text("role = 'clinical_lead'"),
    )
    op.create_table(
        "teaching_org_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("coordinator_email", sa.String(length=255), nullable=False),
        sa.Column("institution_name", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id", name="uq_teaching_org_settings_org"
        ),
    )
    op.create_index(
        op.f("ix_teaching_org_settings_organisation_id"),
        "teaching_org_settings",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "assessment_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("selected_option", sa.String(length=255), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("resolved_tags", sa.JSON(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["question_bank_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_answers_assessment_id"),
        "assessment_answers",
        ["assessment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_assessment_answers_assessment_id"),
        table_name="assessment_answers",
    )
    op.drop_table("assessment_answers")
    op.drop_table("user_role")
    op.drop_index(
        op.f("ix_teaching_org_settings_organisation_id"),
        table_name="teaching_org_settings",
    )
    op.drop_table("teaching_org_settings")
    op.drop_index(
        "ix_site_staff_one_clinical_lead",
        table_name="site_staff_member",
        postgresql_where=sa.text("role = 'clinical_lead'"),
        sqlite_where=sa.text("role = 'clinical_lead'"),
    )
    op.drop_table("site_staff_member")
    op.drop_index(
        op.f("ix_question_bank_syncs_organisation_id"),
        table_name="question_bank_syncs",
    )
    op.drop_table("question_bank_syncs")
    op.drop_index(
        op.f("ix_question_bank_org_status_organisation_id"),
        table_name="question_bank_org_status",
    )
    op.drop_table("question_bank_org_status")
    op.drop_index(
        op.f("ix_question_bank_items_question_bank_id"),
        table_name="question_bank_items",
    )
    op.drop_index(
        op.f("ix_question_bank_items_organisation_id"),
        table_name="question_bank_items",
    )
    op.drop_table("question_bank_items")
    op.drop_index(
        op.f("ix_question_bank_configs_question_bank_id"),
        table_name="question_bank_configs",
    )
    op.drop_index(
        op.f("ix_question_bank_configs_organisation_id"),
        table_name="question_bank_configs",
    )
    op.drop_table("question_bank_configs")
    op.drop_table("push_subscriptions")
    op.drop_table("organisation_staff_member")
    op.drop_table("organisation_site")
    op.drop_table("organisation_patient_member")
    op.drop_index(
        op.f("ix_organisation_features_organisation_id"),
        table_name="organisation_features",
    )
    op.drop_index(
        op.f("ix_organisation_features_feature_key"),
        table_name="organisation_features",
    )
    op.drop_table("organisation_features")
    op.drop_index(
        op.f("ix_messages_fhir_communication_id"), table_name="messages"
    )
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_table("message_organisation")
    op.drop_index(
        op.f("ix_external_patient_access_user_id"),
        table_name="external_patient_access",
    )
    op.drop_index(
        op.f("ix_external_patient_access_patient_id"),
        table_name="external_patient_access",
    )
    op.drop_table("external_patient_access")
    op.drop_index(
        op.f("ix_conversation_participants_user_id"),
        table_name="conversation_participants",
    )
    op.drop_index(
        op.f("ix_conversation_participants_conversation_id"),
        table_name="conversation_participants",
    )
    op.drop_table("conversation_participants")
    op.drop_index(op.f("ix_assessments_user_id"), table_name="assessments")
    op.drop_index(
        op.f("ix_assessments_question_bank_id"), table_name="assessments"
    )
    op.drop_index(
        op.f("ix_assessments_organisation_id"), table_name="assessments"
    )
    op.drop_index(op.f("ix_assessments_exam_ref"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sites_name"), table_name="sites")
    op.drop_table("sites")
    op.drop_table("roles")
    op.drop_index(
        op.f("ix_patient_metadata_patient_id"), table_name="patient_metadata"
    )
    op.drop_table("patient_metadata")
    op.drop_index(op.f("ix_organisations_name"), table_name="organisations")
    op.drop_table("organisations")
    op.drop_index(
        op.f("ix_conversations_patient_id"), table_name="conversations"
    )
    op.drop_index(
        op.f("ix_conversations_fhir_conversation_id"),
        table_name="conversations",
    )
    op.drop_table("conversations")
    # ### end Alembic commands ###
