"""add assessor registration verification table

Revision ID: 3530eb2d528b
Revises: 3c90a58233fd
Create Date: 2026-09-13 08:50:07.535625

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3530eb2d528b"
down_revision: str | None = "3c90a58233fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passport_assessor_registration_verification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "registration_authority", sa.String(length=50), nullable=False
        ),
        sa.Column("registration_number", sa.String(length=50), nullable=False),
        sa.Column("verified_by_user_id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "registration_authority",
            "registration_number",
            "organisation_id",
            name="uq_assessor_registration_verified_here",
        ),
    )
    op.create_index(
        op.f("ix_passport_assessor_registration_verification_organisation_id"),
        "passport_assessor_registration_verification",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_assessor_registration_verification_user_id"),
        "passport_assessor_registration_verification",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passport_assessor_registration_verification_user_id"),
        table_name="passport_assessor_registration_verification",
    )
    op.drop_index(
        op.f("ix_passport_assessor_registration_verification_organisation_id"),
        table_name="passport_assessor_registration_verification",
    )
    op.drop_table("passport_assessor_registration_verification")
    # ### end Alembic commands ###
