"""add passport logbook confirmation request

Revision ID: 6dc732c19c6c
Revises: a712f89d9543
Create Date: 2026-10-07 16:29:45.728685

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dc732c19c6c"
down_revision: str | None = "a712f89d9543"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passport_logbook_confirmation_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("passport_id", sa.String(length=32), nullable=False),
        sa.Column("competency_id", sa.String(length=100), nullable=False),
        sa.Column("entry_stem", sa.String(length=200), nullable=False),
        sa.Column("supervisor_email", sa.String(length=255), nullable=False),
        sa.Column("supervisor_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="open",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["passport_id"], ["passport.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "passport_id",
            "competency_id",
            "entry_stem",
            name="uq_passport_logbook_confirmation_request_entry",
        ),
    )
    op.create_index(
        "ix_passport_logbook_confirmation_request_inbox",
        "passport_logbook_confirmation_request",
        ["supervisor_email", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_logbook_confirmation_request_passport_id"),
        "passport_logbook_confirmation_request",
        ["passport_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_logbook_confirmation_request_supervisor_user_id"),
        "passport_logbook_confirmation_request",
        ["supervisor_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passport_logbook_confirmation_request_supervisor_user_id"),
        table_name="passport_logbook_confirmation_request",
    )
    op.drop_index(
        op.f("ix_passport_logbook_confirmation_request_passport_id"),
        table_name="passport_logbook_confirmation_request",
    )
    op.drop_index(
        "ix_passport_logbook_confirmation_request_inbox",
        table_name="passport_logbook_confirmation_request",
    )
    op.drop_table("passport_logbook_confirmation_request")
    # ### end Alembic commands ###
