"""Add newsletter_send, one row per newsletter sent to one person.

Quill sends its own newsletters, a person at a time. Each row is written
as that person's email leaves, so a send that stops half way can be run
again and reaches only the people it missed.

Revision ID: 7f8cd9d9d82a
Revises: 13369e6db053
Create Date: 2026-10-07 14:02:03.613913

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f8cd9d9d82a"
down_revision: str | None = "13369e6db053"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter_send",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "campaign", "user_id", name="uq_newsletter_send_campaign_user"
        ),
    )
    op.create_index(
        "ix_newsletter_send_user", "newsletter_send", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_newsletter_send_user", table_name="newsletter_send")
    op.drop_table("newsletter_send")
    # ### end Alembic commands ###
