"""add marketing preference

Revision ID: 5b470911f65a
Revises: 4fd333faf33b
Create Date: 2026-10-03 18:17:50.046593

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b470911f65a"
down_revision: str | None = "4fd333faf33b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marketing_preference_change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("wants_marketing", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("wording_version", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_marketing_preference_change_user",
        "marketing_preference_change",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "marketing_emails",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "marketing_synced_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "marketing_synced_at")
    op.drop_column("users", "marketing_emails")
    op.drop_index(
        "ix_marketing_preference_change_user",
        table_name="marketing_preference_change",
    )
    op.drop_table("marketing_preference_change")
    # ### end Alembic commands ###
