"""add professional registration table

One row per professional registration a person has declared, such as a
GMC or NMC number. The expand half of replacing the
`users.professional_registrations` JSON object, which had nowhere to say
when a registration was declared or when it lapsed. Additive: the
application writes rows beside the JSON, and nothing reads them until a
later change. See
docs/docs/plans/2026-09-23-professional-registrations-plan.md.

Revision ID: 2eedb5e4d200
Revises: 2a0640755949
Create Date: 2026-09-24 11:28:36.543364

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2eedb5e4d200"
down_revision: str | None = "2a0640755949"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professional_registration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("authority", sa.String(length=50), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("declared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_professional_registration_user_id"),
        "professional_registration",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_professional_registration_user_id"),
        table_name="professional_registration",
    )
    op.drop_table("professional_registration")
    # ### end Alembic commands ###
