"""add captions reviewed at to module media link

Revision ID: 618a413e034e
Revises: 8931e743f473
Create Date: 2026-09-15 06:40:32.535561

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "618a413e034e"
down_revision: str | None = "8931e743f473"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "module_media_link",
        sa.Column(
            "captions_reviewed_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("module_media_link", "captions_reviewed_at")
    # ### end Alembic commands ###
