"""invitations carry the competency they were raised for

Revision ID: 923c654b5ad1
Revises: 029c6dff773b
Create Date: 2026-09-20 18:45:06.922526

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "923c654b5ad1"
down_revision: str | None = "029c6dff773b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "passport_assessor_invite",
        sa.Column("competency_id", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("passport_assessor_invite", "competency_id")
    # ### end Alembic commands ###
