"""add organisation passport lead frameworks

Revision ID: 405882f25bc5
Revises: 6dc732c19c6c
Create Date: 2026-10-07 18:16:14.060125

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "405882f25bc5"
down_revision: str | None = "6dc732c19c6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_unit_passport_framework",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_unit_id", sa.Integer(), nullable=False),
        sa.Column("framework_id", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_by", sa.Integer(), nullable=True),
        sa.Column("set_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "position >= 1", name="ck_org_unit_passport_framework_position"
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["org_unit.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["set_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_unit_id",
            "framework_id",
            name="uq_org_unit_passport_framework_unit_framework",
        ),
        sa.UniqueConstraint(
            "org_unit_id",
            "position",
            name="uq_org_unit_passport_framework_unit_position",
        ),
    )
    op.create_index(
        op.f("ix_org_unit_passport_framework_org_unit_id"),
        "org_unit_passport_framework",
        ["org_unit_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_org_unit_passport_framework_org_unit_id"),
        table_name="org_unit_passport_framework",
    )
    op.drop_table("org_unit_passport_framework")
    # ### end Alembic commands ###
