"""add feedback table

One row per message a signed-in user sends about the application, with
the context it was sent from and a status an operator moves it through.
Additive: a new table, which nothing reads until the feedback routes do.
See docs/docs/plans/2026-09-20-user-feedback-plan.md.

Revision ID: 79a2c0b0a8c9
Revises: 83c3b5af3ea7
Create Date: 2026-09-23 19:45:38.028732

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79a2c0b0a8c9"
down_revision: str | None = "83c3b5af3ea7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=True),
        sa.Column("message", sa.String(length=5000), nullable=False),
        sa.Column("route", sa.String(length=200), nullable=False),
        sa.Column("release", sa.String(length=100), nullable=False),
        sa.Column("viewport", sa.String(length=20), nullable=False),
        sa.Column("user_agent", sa.String(length=300), nullable=False),
        sa.Column("breadcrumbs", sa.JSON(), nullable=False),
        sa.Column("error_name", sa.String(length=100), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('new', 'acknowledged', 'resolved', 'wont_fix')",
            name="ck_feedback_status_known",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_status"), "feedback", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_feedback_user_id"), "feedback", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_user_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_status"), table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###
