"""add module enrolment

The `module_enrolment` table: one person enrolled on one module an
organisation serves. Teaching asks for a current row before it serves a
module, so the table is filled here for everybody who can enter a module
today, or the deploy would close every module to every delegate. See
`docs/docs/plans/2026-10-04-teaching-access-results-modules-and-enrolment-plan.md`.

Who can enter today: anybody with a `practising_competency` row for
`take_teaching_modules` at an org unit they belong to, for every module
the organisation above that org unit serves (an `active_version` that is
not null). An org unit linked to another by `teaches_at` reaches that
organisation's modules too, one hop, as the application's reach does.
`source` is `migration`.

The table was autogenerated by `just migrate`; the enrolment was added
by hand.

Revision ID: 13369e6db053
Revises: 3d7a91c5e6f2
Create Date: 2026-10-04 20:33:06.568578

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13369e6db053"
down_revision: str | None = "3d7a91c5e6f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "module_enrolment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("org_unit_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("starts_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("granted_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["org_unit.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_module_enrolment_module",
        "module_enrolment",
        ["org_unit_id", "question_bank_id"],
        unique=False,
    )
    op.create_index(
        "ix_module_enrolment_user_module",
        "module_enrolment",
        ["user_id", "org_unit_id", "question_bank_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.execute("""
        WITH RECURSIVE up (start_id, id, parent_id) AS (
            SELECT id, id, parent_id FROM org_unit
            UNION ALL
            SELECT up.start_id, ou.id, ou.parent_id
              FROM up JOIN org_unit AS ou ON ou.id = up.parent_id
        ),
        root_of AS (
            SELECT start_id, id AS root_id FROM up WHERE parent_id IS NULL
        ),
        place AS (
            SELECT pc.user_id, pc.org_unit_id
              FROM practising_competency AS pc
              JOIN org_unit_member AS m
                ON m.org_unit_id = pc.org_unit_id
               AND m.user_id = pc.user_id
             WHERE pc.competency = 'take_teaching_modules'
        ),
        reached AS (
            SELECT p.user_id, r.root_id AS org_id
              FROM place AS p
              JOIN root_of AS r ON r.start_id = p.org_unit_id
            UNION
            SELECT p.user_id, target.root_id
              FROM place AS p
              JOIN root_of AS r ON r.start_id = p.org_unit_id
              JOIN org_unit_link AS l
                ON l.source_id IN (p.org_unit_id, r.root_id)
               AND l.relation = 'teaches_at'
              JOIN root_of AS target ON target.start_id = l.target_id
        )
        INSERT INTO module_enrolment
            (user_id, org_unit_id, question_bank_id, starts_on, source,
             created_at)
        SELECT DISTINCT reached.user_id, s.org_unit_id,
               s.question_bank_id, now(), 'migration', now()
          FROM reached
          JOIN question_bank_org_status AS s
            ON s.org_unit_id = reached.org_id
         WHERE s.active_version IS NOT NULL
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_module_enrolment_user_module", table_name="module_enrolment"
    )
    op.drop_index("ix_module_enrolment_module", table_name="module_enrolment")
    op.drop_table("module_enrolment")
    # ### end Alembic commands ###
