"""backfill practising competencies from membership

The expand half of moving place administration from membership onto
`practising_competency` rows. Nothing reads these rows for authorisation
yet: the switch is a separate change, and it must not deploy until this
has, or every administrator loses access the moment it lands.

Today an administrator reaches a place because they are a member of an
organisation and the place sits somewhere beneath it. That is what
`org_units_administered_by` answers, and it is the set this reproduces as
rows, so behaviour after the switch is the behaviour before it.

Two things this deliberately does not do.

It does not resolve anybody's ceiling. That takes a base profession, a
JSON column of additions and another of removals, combined against a YAML
catalogue, and a migration must not import application code: the code
moves on and the migration has to keep meaning what it meant. So the four
professions granting `manage_users` are named here as literals, correct
when this was written. Somebody granted the competency only through
`additional_competencies` is missed, and is authorised by hand.

It does not write rows for operators. `platform_role = 'superadmin'`
bypasses the place check wherever it is asked, so a row would authorise
nothing it does not already have.

Written by hand rather than autogenerated. There is no model change here,
so `alembic revision --autogenerate` produces an empty `upgrade()`, and
`just migrate` correctly refuses to keep one.

Revision ID: b4c2e7a91f38
Revises: 923c654b5ad1
Create Date: 2026-09-21 15:00:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4c2e7a91f38"
down_revision: str | None = "923c654b5ad1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: The professions whose `base_competencies` include `manage_users` in
#: `shared/base-professions.yaml` when this was written. Frozen as
#: literals because a migration cannot read the catalogue: the file
#: changes, and this migration must go on meaning what it meant.
ADMIN_PROFESSIONS = (
    "clinic_manager",
    "system_administrator",
    "superadmin_profession",
    "teaching_manager",
)

#: What the backfilled rows carry in `authorised_by`, so `downgrade` can
#: recognise its own work. A real authorisation names the person who made
#: it; nobody made these, so NULL is the honest value and it doubles as
#: the marker. `authorised_by` is already nullable, for the case where the
#: authoriser's account is later deleted.
COMPETENCY = "manage_users"

#: The org unit types that can stand at the top of a tree, from
#: `shared/org-unit-types.yaml` when this was written: the ones whose
#: `requires_parent` is false. Frozen as literals for the same reason as
#: the professions above.
#:
#: This matters more than it looks. Membership only confers
#: administration when the place is an *organisation*, and what makes a
#: place one is its type, never that it happens to have no parent. A
#: detached ward has no parent too, and treating it as an organisation
#: would give its members the run of somewhere nobody is accountable for.
ROOT_TYPES = (
    "organisation",
    "hospital_team",
    "gp_practice",
    "private_clinic",
    "teaching_establishment",
)


def upgrade() -> None:
    """Authorise `manage_users` wherever membership implies it today.

    One statement. The recursive term walks down from each administrator's
    organisations, so a place at any depth is covered and a third level of
    tree needs no change here.

    Idempotent: the `NOT EXISTS` clause skips a pair already authorised,
    whether by an earlier run of this migration or by hand, so re-running
    adds nothing and overwrites nothing.
    """
    professions = ", ".join(f"'{p}'" for p in ADMIN_PROFESSIONS)
    root_types = ", ".join(f"'{t}'" for t in ROOT_TYPES)

    op.execute(f"""
        WITH RECURSIVE admins AS (
            SELECT id AS user_id
              FROM users
             WHERE base_profession IN ({professions})
               AND platform_role <> 'superadmin'
               AND is_active = true
        ),
        roots AS (
            -- Only membership of an organisation confers administration.
            -- A membership of a ward is a fact about the ward and reaches
            -- nothing, because reach runs downward only.
            SELECT a.user_id, m.org_unit_id
              FROM admins a
              JOIN org_unit_member m ON m.user_id = a.user_id
              JOIN org_unit o ON o.id = m.org_unit_id
             WHERE o.type IN ({root_types})
        ),
        reach AS (
            SELECT user_id, org_unit_id
              FROM roots
             UNION
            SELECT r.user_id, o.id
              FROM reach r
              JOIN org_unit o ON o.parent_id = r.org_unit_id
        )
        INSERT INTO practising_competency
            (user_id, org_unit_id, competency, authorised_by, authorised_at)
        SELECT DISTINCT
               reach.user_id,
               reach.org_unit_id,
               '{COMPETENCY}',
               -- Cast required: a bare NULL in a SELECT is typed as text,
               -- and the column is an integer foreign key.
               CAST(NULL AS integer),
               NOW()
          FROM reach
         WHERE NOT EXISTS (
                   SELECT 1
                     FROM practising_competency existing
                    WHERE existing.user_id = reach.user_id
                      AND existing.org_unit_id = reach.org_unit_id
                      AND existing.competency = '{COMPETENCY}'
               )
    """)


def downgrade() -> None:
    """Remove only the rows this migration created.

    `authorised_by IS NULL` is what marks them: every row written by the
    API names the person who authorised it, and these name nobody because
    nobody did. A row whose authoriser was later deleted also has NULL
    here, so such a row would be removed too. That is accepted: it is the
    same competency at a place the person administers anyway, and the
    alternative is a marker column carried forever for one migration's
    benefit.

    Rows authorised by hand keep their author and survive, which is the
    property that matters.
    """
    op.execute(f"""
        DELETE FROM practising_competency
         WHERE competency = '{COMPETENCY}'
           AND authorised_by IS NULL
    """)
