"""add reply seen times to feedback

Revision ID: 7d0086c2b783
Revises: 8c1f4e2a9b37
Create Date: 2026-10-04 20:10:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d0086c2b783"
down_revision: str | None = "8c1f4e2a9b37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedback",
        sa.Column(
            "operator_comment_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "feedback",
        sa.Column(
            "comment_seen_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedback", "comment_seen_at")
    op.drop_column("feedback", "operator_comment_at")
    # ### end Alembic commands ###
