"""record where a competency may be practised

One row per person, place and competency: what someone is authorised to
practise here, as opposed to what they are qualified for anywhere. The
ceiling stays on the user; this is the second half, and it is the same line
healthcare draws between credentialing and privileging.

Deliberately not called a grant. The organisation does not confer the
competency — the person holds that — so a row only records that they may
exercise it at this place.

Exactly one of organisation_id and site_id is set, enforced by a check
constraint rather than by convention. A shared "places" table was rejected
because it would need a row for every organisation and site forever, and a
missed one would make that place invisible to the permission system.

Uniqueness is two partial indexes rather than one four-column constraint: a
place column is always NULL and SQL treats NULLs as distinct, so a single
constraint would never fire.

Purely additive. Nothing reads the table yet, so no backfill: an empty table
means nothing is authorised anywhere, and the existing global competency
check is untouched until call sites move over one at a time.

Revision ID: 51e2994da89d
Revises: adb43829b601
Create Date: 2026-09-08 06:18:48.958871

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51e2994da89d"
down_revision: str | None = "adb43829b601"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practising_competency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("competency", sa.String(length=100), nullable=False),
        sa.Column("authorised_by", sa.Integer(), nullable=True),
        sa.Column("authorised_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(organisation_id IS NOT NULL) <> (site_id IS NOT NULL)",
            name="ck_practising_competency_one_place",
        ),
        sa.ForeignKeyConstraint(
            ["authorised_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_practising_competency_org",
        "practising_competency",
        ["organisation_id", "competency"],
        unique=False,
    )
    op.create_index(
        "ix_practising_competency_site",
        "practising_competency",
        ["site_id", "competency"],
        unique=False,
    )
    op.create_index(
        "ix_practising_competency_user",
        "practising_competency",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_practising_competency_org",
        "practising_competency",
        ["user_id", "organisation_id", "competency"],
        unique=True,
        postgresql_where=sa.text("organisation_id IS NOT NULL"),
        sqlite_where=sa.text("organisation_id IS NOT NULL"),
    )
    op.create_index(
        "uq_practising_competency_site",
        "practising_competency",
        ["user_id", "site_id", "competency"],
        unique=True,
        postgresql_where=sa.text("site_id IS NOT NULL"),
        sqlite_where=sa.text("site_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_practising_competency_site",
        table_name="practising_competency",
        postgresql_where=sa.text("site_id IS NOT NULL"),
        sqlite_where=sa.text("site_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_practising_competency_org",
        table_name="practising_competency",
        postgresql_where=sa.text("organisation_id IS NOT NULL"),
        sqlite_where=sa.text("organisation_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_practising_competency_user", table_name="practising_competency"
    )
    op.drop_index(
        "ix_practising_competency_site", table_name="practising_competency"
    )
    op.drop_index(
        "ix_practising_competency_org", table_name="practising_competency"
    )
    op.drop_table("practising_competency")
    # ### end Alembic commands ###
