"""backfill user_competency from the JSON lists and entitlements

Copies every user's `additional_competencies` and `removed_competencies`
into `user_competency` rows, and every `passport_write_entitlement` row
into a dated `passport_write` row. Nothing reads the rows yet: switching
reads is a separate change, and it must not deploy until this has.

The application has been writing rows beside the JSON since the change
before this one, so the table is not empty when this runs. Anybody saved
since then already has rows matching their lists, and every insert below
skips what is already there rather than assuming a blank table.

Three things this deliberately does.

`passport_write` in `additional_competencies` is not copied. A holder has
it in the JSON *and* in an entitlement row, and copying both would write
one row with no end date beside one with a date. An undated row is
current forever, so the entitlement would never lapse. The entitlement
is the only thing copied for it.

An entitlement belonging to somebody whose lists do not grant
`passport_write` is copied closed. Today such a person cannot write, because
the gate asks for the competency as well as the term. A copy left open
would give them the competency back the moment reads move to rows; a copy
left out would lose the record of the term when the entitlement table is
dropped. Closed, it keeps both facts.

Stale ids are carried across. A competency the catalogue no longer has
is copied like any other, because losing a grant silently during a
storage change is worse than carrying one that means nothing.
`unknown_ids_on_users` in `app/cbac/audit.py` reports them either side of
this.

Written by hand rather than autogenerated. There is no model change here,
so `just migrate` would correctly refuse an empty `upgrade()`.

Revision ID: 61e9c9b15ac6
Revises: baff1a11eeb2
Create Date: 2026-09-23 13:34:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61e9c9b15ac6"
down_revision: str | None = "baff1a11eeb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: The competency whose grant must carry a term. Frozen as a literal: a
#: migration must go on meaning what it meant when written, whatever the
#: application later calls it.
TERMED = "passport_write"

#: The `source` values this migration writes, and so the ones `downgrade`
#: removes. `migrated` for the JSON lists; the entitlement copies keep the
#: entitlement's own `organisation` or `individual`.
SOURCES = ("migrated", "organisation", "individual")


def _elements(column: str) -> str:
    """The ids in one JSON list column of `users u`, as a set of rows.

    Guarded against a value that is not an array, which
    `json_array_elements_text` would otherwise raise on and fail the whole
    deploy for one bad row. Such a value holds no ids to copy.
    """
    return (
        "json_array_elements_text("
        f"CASE WHEN json_typeof(u.{column}) = 'array' "
        f"THEN u.{column} ELSE '[]'::json END)"
    )


def _copy_list(column: str, *, granted: bool) -> str:
    """Copy one JSON list column into rows, skipping what is there.

    A user already has an entry when they have a *current* row for the
    same competency with the same `granted`. That covers a re-run of this
    migration and every user the dual-write has brought into line. A
    closed row does not count: somebody whose grant was taken away and
    later given back through the JSON has a current grant to copy.
    """
    flag = "true" if granted else "false"
    skip_termed = f"AND ids.value <> '{TERMED}'" if granted else ""
    return f"""
        INSERT INTO user_competency
            (user_id, competency_id, granted, starts_on, ends_on,
             source, org_unit_id, granted_by, created_at)
        SELECT DISTINCT
               u.id,
               ids.value,
               {flag},
               CAST(NULL AS timestamptz),
               CAST(NULL AS timestamptz),
               'migrated',
               CAST(NULL AS integer),
               CAST(NULL AS integer),
               NOW()
          FROM users u
         CROSS JOIN LATERAL {_elements(column)} AS ids(value)
         WHERE ids.value <> ''
           {skip_termed}
           AND NOT EXISTS (
                   SELECT 1
                     FROM user_competency existing
                    WHERE existing.user_id = u.id
                      AND existing.competency_id = ids.value
                      AND existing.granted = {flag}
                      AND (existing.ends_on IS NULL
                           OR existing.ends_on > NOW())
               )
    """


def _copy_entitlements() -> str:
    """Copy every entitlement into a dated `passport_write` row.

    An entitlement is recognised as already copied by its person, start
    and source. The dual-write mirrors each new entitlement with exactly
    those values, so this also skips everything written since the table
    arrived. The start rather than the end, because a copy closed here no
    longer carries the entitlement's end.

    `holds` is whether the person's lists grant `passport_write` today:
    in `additional_competencies` and not in `removed_competencies`. No
    base profession grants it, so the lists are the whole answer.
    """
    return f"""
        INSERT INTO user_competency
            (user_id, competency_id, granted, starts_on, ends_on,
             source, org_unit_id, granted_by, created_at)
        SELECT e.user_id,
               '{TERMED}',
               true,
               e.starts_on,
               CASE
                   WHEN holds.value THEN e.ends_on
                   -- Closed, not dropped: see the module docstring.
                   -- GREATEST keeps a start in the future valid against
                   -- `ck_user_competency_ends_after_start`.
                   ELSE GREATEST(e.starts_on, LEAST(e.ends_on, NOW()))
               END,
               e.source,
               e.org_unit_id,
               CAST(NULL AS integer),
               NOW()
          FROM passport_write_entitlement e
          JOIN users u ON u.id = e.user_id
         CROSS JOIN LATERAL (
               SELECT EXISTS (
                          SELECT 1
                            FROM {_elements("additional_competencies")}
                              AS a(value)
                           WHERE a.value = '{TERMED}'
                      )
                  AND NOT EXISTS (
                          SELECT 1
                            FROM {_elements("removed_competencies")}
                              AS r(value)
                           WHERE r.value = '{TERMED}'
                      ) AS value
         ) AS holds
         WHERE NOT EXISTS (
                   SELECT 1
                     FROM user_competency existing
                    WHERE existing.user_id = e.user_id
                      AND existing.competency_id = '{TERMED}'
                      AND existing.granted = true
                      AND existing.starts_on = e.starts_on
                      AND existing.source = e.source
               )
    """


def upgrade() -> None:
    """Copy both JSON lists and every entitlement into rows.

    Idempotent: each statement skips what is already there, so re-running
    adds nothing.
    """
    op.execute(_copy_list("additional_competencies", granted=True))
    op.execute(_copy_list("removed_competencies", granted=False))
    op.execute(_copy_entitlements())


def downgrade() -> None:
    """Remove only the rows this migration wrote.

    What marks them is a null `granted_by` together with one of the sources
    this migration writes. The dual-write names the administrator on every
    `admin` and `organisation` row it writes, and writes `operator` and
    `bootstrap` for the rest, so none of its rows match and they survive a
    downgrade.
    """
    sources = ", ".join(f"'{s}'" for s in SOURCES)
    op.execute(f"""
        DELETE FROM user_competency
         WHERE granted_by IS NULL
           AND source IN ({sources})
    """)
