"""passport write entitlements carry an end date

Revision ID: 02ee55a90547
Revises: b4c2e7a91f38
Create Date: 2026-09-21 17:55:45.018188

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02ee55a90547"
down_revision: str | None = "b4c2e7a91f38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passport_write_entitlement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("org_unit_id", sa.Integer(), nullable=True),
        sa.Column("starts_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source IN ('organisation', 'individual')",
            name="ck_passport_write_entitlement_source",
        ),
        sa.CheckConstraint(
            "ends_on > starts_on",
            name="ck_passport_write_entitlement_ends_after_start",
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["org_unit.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passport_write_entitlement_ends_on"),
        "passport_write_entitlement",
        ["ends_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_write_entitlement_org_unit_id"),
        "passport_write_entitlement",
        ["org_unit_id"],
        unique=False,
    )
    op.create_index(
        "ix_passport_write_entitlement_user_ends",
        "passport_write_entitlement",
        ["user_id", "ends_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_write_entitlement_user_id"),
        "passport_write_entitlement",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passport_write_entitlement_user_id"),
        table_name="passport_write_entitlement",
    )
    op.drop_index(
        "ix_passport_write_entitlement_user_ends",
        table_name="passport_write_entitlement",
    )
    op.drop_index(
        op.f("ix_passport_write_entitlement_org_unit_id"),
        table_name="passport_write_entitlement",
    )
    op.drop_index(
        op.f("ix_passport_write_entitlement_ends_on"),
        table_name="passport_write_entitlement",
    )
    op.drop_table("passport_write_entitlement")
    # ### end Alembic commands ###
