"""add passport assessor invite table

Revision ID: 3c90a58233fd
Revises: b4d1e9c72a05
Create Date: 2026-09-13 07:50:08.202457

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c90a58233fd"
down_revision: str | None = "b4d1e9c72a05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passport_assessor_invite",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("passport_id", sa.String(length=32), nullable=False),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "registration_authority", sa.String(length=50), nullable=False
        ),
        sa.Column("registration_number", sa.String(length=50), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accepted_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["passport_id"], ["passport.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passport_assessor_invite_accepted_user_id"),
        "passport_assessor_invite",
        ["accepted_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_assessor_invite_invited_by_user_id"),
        "passport_assessor_invite",
        ["invited_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_assessor_invite_passport_id"),
        "passport_assessor_invite",
        ["passport_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_assessor_invite_token_hash"),
        "passport_assessor_invite",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passport_assessor_invite_token_hash"),
        table_name="passport_assessor_invite",
    )
    op.drop_index(
        op.f("ix_passport_assessor_invite_passport_id"),
        table_name="passport_assessor_invite",
    )
    op.drop_index(
        op.f("ix_passport_assessor_invite_invited_by_user_id"),
        table_name="passport_assessor_invite",
    )
    op.drop_index(
        op.f("ix_passport_assessor_invite_accepted_user_id"),
        table_name="passport_assessor_invite",
    )
    op.drop_table("passport_assessor_invite")
    # ### end Alembic commands ###
