"""add positions and who holds them

A position is a slot an organisation or site has — clinical lead, Caldicott
Guardian — which exists whether or not anyone fills it. That is what
separates it from a competency: a vacancy is a state worth chasing, where a
competency nobody holds is simply absent.

Holding is a separate table of dated rows rather than a column on the
position, so the post outlives its holders and its history stays queryable.
An acting holding sits alongside the substantive one rather than replacing
it, so the record still shows whose post it is.

Exactly one of organisation_id and site_id is set on a position, matching
practising_competency and enforced the same way. Uniqueness is two partial
indexes for the same reason: one place column is always NULL and SQL treats
NULLs as distinct.

Purely additive, and nothing reads these tables yet. site_staff_member.role
still carries clinical_lead and is untouched here; moving its two consumers
across is separate work.

Revision ID: c067f8e61534
Revises: 51e2994da89d
Create Date: 2026-09-08 13:25:39.687103

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c067f8e61534"
down_revision: str | None = "51e2994da89d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("requires_competency", sa.String(length=100), nullable=True),
        sa.Column("max_holders", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(organisation_id IS NOT NULL) <> (site_id IS NOT NULL)",
            name="ck_position_one_place",
        ),
        sa.CheckConstraint(
            "max_holders IS NULL OR max_holders > 0",
            name="ck_position_max_holders_positive",
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_position_org_kind",
        "position",
        ["organisation_id", "kind"],
        unique=True,
        postgresql_where=sa.text("organisation_id IS NOT NULL"),
        sqlite_where=sa.text("organisation_id IS NOT NULL"),
    )
    op.create_index(
        "uq_position_site_kind",
        "position",
        ["site_id", "kind"],
        unique=True,
        postgresql_where=sa.text("site_id IS NOT NULL"),
        sqlite_where=sa.text("site_id IS NOT NULL"),
    )
    op.create_table(
        "position_holding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("ended_on", sa.Date(), nullable=True),
        sa.Column("is_acting", sa.Boolean(), nullable=False),
        sa.Column("appointed_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "ended_on IS NULL OR ended_on >= started_on",
            name="ck_position_holding_dates_ordered",
        ),
        sa.ForeignKeyConstraint(
            ["appointed_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["position.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_position_holding_position",
        "position_holding",
        ["position_id"],
        unique=False,
    )
    op.create_index(
        "ix_position_holding_user",
        "position_holding",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_position_holding_user", table_name="position_holding")
    op.drop_index(
        "ix_position_holding_position", table_name="position_holding"
    )
    op.drop_table("position_holding")
    op.drop_index(
        "uq_position_site_kind",
        table_name="position",
        postgresql_where=sa.text("site_id IS NOT NULL"),
        sqlite_where=sa.text("site_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_position_org_kind",
        table_name="position",
        postgresql_where=sa.text("organisation_id IS NOT NULL"),
        sqlite_where=sa.text("organisation_id IS NOT NULL"),
    )
    op.drop_table("position")
    # ### end Alembic commands ###
