"""add assessment answer tag table

One row per tag of the option a candidate chose, per answer. The expand
half of replacing the `assessment_answers.resolved_tags` JSON column,
which the database cannot see into, so no question across attempts can
be asked of it. Additive: the application writes rows beside the JSON,
and scoring keeps reading the JSON until a later change. See
docs/docs/plans/2026-09-23-resolved-tags-plan.md.

Revision ID: aa35480f3d40
Revises: 57deea9f9ea6
Create Date: 2026-09-23 19:19:56.349148

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa35480f3d40"
down_revision: str | None = "57deea9f9ea6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_answer_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answer_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["assessment_answers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "answer_id", "tag", name="uq_assessment_answer_tag_answer_tag"
        ),
    )
    op.create_index(
        op.f("ix_assessment_answer_tag_answer_id"),
        "assessment_answer_tag",
        ["answer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_answer_tag_tag"),
        "assessment_answer_tag",
        ["tag"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_assessment_answer_tag_tag"),
        table_name="assessment_answer_tag",
    )
    op.drop_index(
        op.f("ix_assessment_answer_tag_answer_id"),
        table_name="assessment_answer_tag",
    )
    op.drop_table("assessment_answer_tag")
    # ### end Alembic commands ###
