"""add clinician passport tables

Revision ID: 9892b8ab6290
Revises: 4937cb81e5ae
Create Date: 2026-09-11 11:49:41.884097

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9892b8ab6290"
down_revision: str | None = "4937cb81e5ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passport",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("head_commit", sa.String(length=40), nullable=True),
        sa.Column("storage_generation", sa.Integer(), nullable=True),
        sa.CheckConstraint("length(id) = 32", name="ck_passport_id_is_32_hex"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passport_user_id"), "passport", ["user_id"], unique=True
    )
    op.create_table(
        "site_common_competency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("organisation_id", sa.Integer(), nullable=True),
        sa.Column("competency_id", sa.String(length=100), nullable=False),
        sa.Column(
            "position", sa.Integer(), server_default="0", nullable=False
        ),
        sa.CheckConstraint(
            "(site_id IS NULL) <> (organisation_id IS NULL)",
            name="ck_site_common_competency_one_place",
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organisations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id",
            "competency_id",
            name="uq_site_common_competency_org",
        ),
        sa.UniqueConstraint(
            "site_id", "competency_id", name="uq_site_common_competency_site"
        ),
    )
    op.create_index(
        op.f("ix_site_common_competency_organisation_id"),
        "site_common_competency",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_common_competency_site_id"),
        "site_common_competency",
        ["site_id"],
        unique=False,
    )
    op.create_table(
        "passport_signoff_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("passport_id", sa.String(length=32), nullable=False),
        sa.Column("signoff_id", sa.String(length=200), nullable=False),
        sa.Column("competency_id", sa.String(length=100), nullable=False),
        sa.Column("assessor_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="open",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessor_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["passport_id"], ["passport.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "passport_id",
            "signoff_id",
            name="uq_passport_signoff_request_folder",
        ),
    )
    op.create_index(
        op.f("ix_passport_signoff_request_assessor_user_id"),
        "passport_signoff_request",
        ["assessor_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_passport_signoff_request_inbox",
        "passport_signoff_request",
        ["assessor_user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passport_signoff_request_passport_id"),
        "passport_signoff_request",
        ["passport_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passport_signoff_request_passport_id"),
        table_name="passport_signoff_request",
    )
    op.drop_index(
        "ix_passport_signoff_request_inbox",
        table_name="passport_signoff_request",
    )
    op.drop_index(
        op.f("ix_passport_signoff_request_assessor_user_id"),
        table_name="passport_signoff_request",
    )
    op.drop_table("passport_signoff_request")
    op.drop_index(
        op.f("ix_site_common_competency_site_id"),
        table_name="site_common_competency",
    )
    op.drop_index(
        op.f("ix_site_common_competency_organisation_id"),
        table_name="site_common_competency",
    )
    op.drop_table("site_common_competency")
    op.drop_index(op.f("ix_passport_user_id"), table_name="passport")
    op.drop_table("passport")
    # ### end Alembic commands ###
