"""add operator comment to feedback

Revision ID: 2736214b7eb1
Revises: 5b470911f65a
Create Date: 2026-10-04 15:00:25.467278

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2736214b7eb1"
down_revision: str | None = "5b470911f65a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedback",
        sa.Column("operator_comment", sa.String(length=2000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedback", "operator_comment")
    # ### end Alembic commands ###
