"""add user_competency table

One row per competency granted to, or removed from, one person. The
expand half of replacing the `additional_competencies` and
`removed_competencies` JSON columns on `users`, which could not say when
a grant started, when it ends or who made it. Additive: the table starts
empty, the application writes rows beside the JSON, and nothing reads
them until a later change. See
docs/docs/plans/2026-09-23-user-competency-table-plan.md.

Revision ID: baff1a11eeb2
Revises: dcc9fd1b7cd2
Create Date: 2026-09-23 12:22:44.025963

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baff1a11eeb2"
down_revision: str | None = "dcc9fd1b7cd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_competency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.String(length=100), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("starts_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("org_unit_id", sa.Integer(), nullable=True),
        sa.Column("granted_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on",
            name="ck_user_competency_ends_after_start",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["org_unit.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_competency_competency_id"),
        "user_competency",
        ["competency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_competency_user_id"),
        "user_competency",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_competency_user_id"), table_name="user_competency"
    )
    op.drop_index(
        op.f("ix_user_competency_competency_id"), table_name="user_competency"
    )
    op.drop_table("user_competency")
    # ### end Alembic commands ###
