"""add job start times to module media link

Revision ID: f990809f3524
Revises: 618a413e034e
Create Date: 2026-09-17 16:53:56.414432

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f990809f3524"
down_revision: str | None = "618a413e034e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "module_media_link",
        sa.Column(
            "transcode_started_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "module_media_link",
        sa.Column(
            "caption_started_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("module_media_link", "caption_started_at")
    op.drop_column("module_media_link", "transcode_started_at")
    # ### end Alembic commands ###
