"""sign-off requests name their assessor by email

Revision ID: 427687ff1b36
Revises: f990809f3524
Create Date: 2026-09-17 21:03:09.342193

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "427687ff1b36"
down_revision: str | None = "f990809f3524"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "passport_signoff_request",
        sa.Column(
            "assessor_email",
            sa.String(length=255),
            server_default="",
            nullable=False,
        ),
    )
    op.alter_column(
        "passport_signoff_request",
        "assessor_user_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_passport_signoff_request_inbox"),
        table_name="passport_signoff_request",
    )
    op.create_index(
        "ix_passport_signoff_request_inbox",
        "passport_signoff_request",
        ["assessor_email", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_passport_signoff_request_inbox",
        table_name="passport_signoff_request",
    )
    op.create_index(
        op.f("ix_passport_signoff_request_inbox"),
        "passport_signoff_request",
        ["assessor_user_id", "status"],
        unique=False,
    )
    op.alter_column(
        "passport_signoff_request",
        "assessor_user_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("passport_signoff_request", "assessor_email")
    # ### end Alembic commands ###
