"""add transcode state to module media link

Revision ID: ab53ececc274
Revises: 3530eb2d528b
Create Date: 2026-09-13 20:38:50.952371

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab53ececc274"
down_revision: str | None = "3530eb2d528b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "module_media_link",
        sa.Column("transcoded_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "module_media_link",
        sa.Column(
            "has_1080p",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "module_media_link",
        sa.Column(
            "has_poster",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "module_media_link",
        sa.Column(
            "has_captions",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("module_media_link", "has_captions")
    op.drop_column("module_media_link", "has_poster")
    op.drop_column("module_media_link", "has_1080p")
    op.drop_column("module_media_link", "transcoded_at")
    # ### end Alembic commands ###
