"""teaching email branding

How emails sent for a teaching organisation show it: a short name for the
sender line ("EoEETA via Quill Medical"), and a logo with its width for the
partner strip under the header. Additive and nullable, so every existing
row stays valid and sends as it did. See
docs/docs/plans/2026-09-25-email-branding-plan.md.

Revision ID: 3fb0540ae00c
Revises: 5871099a909e
Create Date: 2026-09-25 18:55:37.604224

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fb0540ae00c"
down_revision: str | None = "5871099a909e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teaching_org_settings",
        sa.Column("email_short_name", sa.String(length=40), nullable=True),
    )
    op.add_column(
        "teaching_org_settings",
        sa.Column("email_logo", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "teaching_org_settings",
        sa.Column("email_logo_width", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teaching_org_settings", "email_logo_width")
    op.drop_column("teaching_org_settings", "email_logo")
    op.drop_column("teaching_org_settings", "email_short_name")
    # ### end Alembic commands ###
