"""add typed links between places

Everything that is not ownership: a medical school teaching on a trust's
wards, two trusts sharing a laboratory. Ownership stays the parent column,
so that who is accountable for a place has one answer; a second
relationship becomes a row here rather than a second parent.

Both ends point at ``sites``, which is the table the org_unit tree is
being built in — organisations become rows there in a later step, so a
school-to-trust link becomes expressible without this table changing.

There is nothing to migrate into it. The step that gave each site one
owner refuses to run at all while any site belongs to two organisations,
so by the time this arrives there are none left to carry across.

Revision ID: e569c426442c
Revises: 09b1d53782d3
Create Date: 2026-09-16 13:16:40.894656

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e569c426442c"
down_revision: str | None = "09b1d53782d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_unit_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_id <> target_id", name="ck_org_unit_link_not_self"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sites.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["sites.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id",
            "target_id",
            "relation",
            name="uq_org_unit_link_triple",
        ),
    )
    op.create_index(
        op.f("ix_org_unit_link_source_id"),
        "org_unit_link",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_org_unit_link_target_id"),
        "org_unit_link",
        ["target_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_org_unit_link_target_id"), table_name="org_unit_link"
    )
    op.drop_index(
        op.f("ix_org_unit_link_source_id"), table_name="org_unit_link"
    )
    op.drop_table("org_unit_link")
    # ### end Alembic commands ###
