"""

Revision ID: 58e3011782fa
Revises: org001
Create Date: 2026-03-22 09:58:36.802378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58e3011782fa"
down_revision: Union[str, None] = "org001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("bank_version", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("score_breakdown", sa.JSON(), nullable=True),
        sa.Column("is_passed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_organisation_id"),
        "assessments",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessments_question_bank_id"),
        "assessments",
        ["question_bank_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessments_user_id"),
        "assessments",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "organisation_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("feature_key", sa.String(length=50), nullable=False),
        sa.Column("enabled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enabled_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id", "feature_key", name="uq_org_feature"
        ),
    )
    op.create_index(
        op.f("ix_organisation_features_feature_key"),
        "organisation_features",
        ["feature_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organisation_features_organisation_id"),
        "organisation_features",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "question_bank_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("config_yaml", sa.JSON(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["synced_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id",
            "question_bank_id",
            "version",
            name="uq_qb_config_org_bank_ver",
        ),
    )
    op.create_index(
        op.f("ix_question_bank_configs_organisation_id"),
        "question_bank_configs",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_configs_question_bank_id"),
        "question_bank_configs",
        ["question_bank_id"],
        unique=False,
    )
    op.create_table(
        "question_bank_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("bank_version", sa.Integer(), nullable=False),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_option_id", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_bank_items_organisation_id"),
        "question_bank_items",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_items_question_bank_id"),
        "question_bank_items",
        ["question_bank_id"],
        unique=False,
    )
    op.create_table(
        "question_bank_syncs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("question_bank_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("items_created", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_bank_syncs_organisation_id"),
        "question_bank_syncs",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "teaching_org_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("coordinator_email", sa.String(length=255), nullable=False),
        sa.Column("institution_name", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organisation_id", name="uq_teaching_org_settings_org"
        ),
    )
    op.create_index(
        op.f("ix_teaching_org_settings_organisation_id"),
        "teaching_org_settings",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "assessment_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("selected_option", sa.String(length=255), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("resolved_tags", sa.JSON(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["question_bank_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_answers_assessment_id"),
        "assessment_answers",
        ["assessment_id"],
        unique=False,
    )
    op.alter_column(
        "conversation_participants",
        "role",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'participant'::character varying"),
    )
    op.alter_column(
        "conversation_participants",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversation_participants",
        "last_read_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("uq_conversation_participant"),
        "conversation_participants",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_conv_participant",
        "conversation_participants",
        ["conversation_id", "user_id"],
    )
    op.drop_constraint(
        op.f("conversation_participants_user_id_fkey"),
        "conversation_participants",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("conversation_participants_conversation_id_fkey"),
        "conversation_participants",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "conversation_participants",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "conversation_participants",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "conversations",
        "fhir_conversation_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "patient_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "subject",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "status",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'new'::character varying"),
    )
    op.alter_column(
        "conversations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "messages",
        "fhir_communication_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "body",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "redacted_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "messages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("messages_conversation_id_fkey"), "messages", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("messages_sender_id_fkey"), "messages", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "messages",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "messages", "users", ["sender_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "messages", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(
        op.f("messages_sender_id_fkey"),
        "messages",
        "users",
        ["sender_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("messages_conversation_id_fkey"),
        "messages",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    op.alter_column(
        "messages",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "messages",
        "redacted_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "messages",
        "body",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "fhir_communication_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversations",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversations",
        "status",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
        existing_server_default=sa.text("'new'::character varying"),
    )
    op.alter_column(
        "conversations",
        "subject",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "patient_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "fhir_conversation_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.drop_constraint(None, "conversation_participants", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "conversation_participants", type_="foreignkey")  # type: ignore[arg-type]
    op.create_foreign_key(
        op.f("conversation_participants_conversation_id_fkey"),
        "conversation_participants",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("conversation_participants_user_id_fkey"),
        "conversation_participants",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_conv_participant", "conversation_participants", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_conversation_participant"),
        "conversation_participants",
        ["conversation_id", "user_id"],
    )
    op.alter_column(
        "conversation_participants",
        "last_read_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "conversation_participants",
        "joined_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conversation_participants",
        "role",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
        existing_server_default=sa.text("'participant'::character varying"),
    )
    op.drop_index(
        op.f("ix_assessment_answers_assessment_id"),
        table_name="assessment_answers",
    )
    op.drop_table("assessment_answers")
    op.drop_index(
        op.f("ix_teaching_org_settings_organisation_id"),
        table_name="teaching_org_settings",
    )
    op.drop_table("teaching_org_settings")
    op.drop_index(
        op.f("ix_question_bank_syncs_organisation_id"),
        table_name="question_bank_syncs",
    )
    op.drop_table("question_bank_syncs")
    op.drop_index(
        op.f("ix_question_bank_items_question_bank_id"),
        table_name="question_bank_items",
    )
    op.drop_index(
        op.f("ix_question_bank_items_organisation_id"),
        table_name="question_bank_items",
    )
    op.drop_table("question_bank_items")
    op.drop_index(
        op.f("ix_question_bank_configs_question_bank_id"),
        table_name="question_bank_configs",
    )
    op.drop_index(
        op.f("ix_question_bank_configs_organisation_id"),
        table_name="question_bank_configs",
    )
    op.drop_table("question_bank_configs")
    op.drop_index(
        op.f("ix_organisation_features_organisation_id"),
        table_name="organisation_features",
    )
    op.drop_index(
        op.f("ix_organisation_features_feature_key"),
        table_name="organisation_features",
    )
    op.drop_table("organisation_features")
    op.drop_index(op.f("ix_assessments_user_id"), table_name="assessments")
    op.drop_index(
        op.f("ix_assessments_question_bank_id"), table_name="assessments"
    )
    op.drop_index(
        op.f("ix_assessments_organisation_id"), table_name="assessments"
    )
    op.drop_table("assessments")
    # ### end Alembic commands ###
