"""adding TOTP

Revision ID: 61bc37adb8f7
Revises: 49c5bacfa481
Create Date: 2025-09-20 15:37:20.108031

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61bc37adb8f7"
down_revision: str | None = "49c5bacfa481"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("totp_secret", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "users", sa.Column("is_totp_enabled", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_totp_enabled")
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
