"""adding TOTP

Revision ID: 61bc37adb8f7
Revises: 49c5bacfa481
Create Date: 2025-09-20 15:37:20.108031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bc37adb8f7'
down_revision: Union[str, None] = '49c5bacfa481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('is_totp_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
