"""add site_registration to question_bank_org_status

Revision ID: 7a44a91ac55a
Revises: 3f28ddb4031e
Create Date: 2026-05-20 12:35:19.617631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7a44a91ac55a"
down_revision: Union[str, None] = "3f28ddb4031e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_bank_org_status",
        sa.Column(
            "site_registration",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_bank_org_status", "site_registration")
    # ### end Alembic commands ###
