"""updates for mypy

Revision ID: 8a6bfd7b4ce9
Revises: 055bc31fb937
Create Date: 2025-09-26 06:07:36.718350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6bfd7b4ce9'
down_revision: Union[str, None] = '055bc31fb937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
