"""add question_bank_org_status table

Revision ID: 8e5f0b755530
Revises: 58e3011782fa
Create Date: 2026-03-29 21:28:46.966732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5f0b755530'
down_revision: Union[str, None] = '58e3011782fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank_org_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('question_bank_id', sa.String(length=255), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'question_bank_id', name='uq_qb_org_status_org_bank')
    )
    op.create_index(op.f('ix_question_bank_org_status_organisation_id'), 'question_bank_org_status', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_bank_org_status_organisation_id'), table_name='question_bank_org_status')
    op.drop_table('question_bank_org_status')
    # ### end Alembic commands ###
