"""updates for mypy

Revision ID: ce0e2ca7d2ca
Revises: 6a4b0e5b7e7f
Create Date: 2025-09-26 06:06:59.038785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0e2ca7d2ca'
down_revision: Union[str, None] = '6a4b0e5b7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
