"""add exam_ref to assessments

Revision ID: d281376e497d
Revises: f98e1c93dcd7
Create Date: 2026-04-01 05:54:05.937768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd281376e497d'
down_revision: Union[str, None] = 'f98e1c93dcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('exam_ref', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_assessments_exam_ref'), 'assessments', ['exam_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_exam_ref'), table_name='assessments')
    op.drop_column('assessments', 'exam_ref')
    # ### end Alembic commands ###
