"""

Revision ID: f98e1c93dcd7
Revises: 8e5f0b755530
Create Date: 2026-03-30 21:26:59.336203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98e1c93dcd7'
down_revision: Union[str, None] = '8e5f0b755530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank_org_status', sa.Column('coordinator_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_bank_org_status', 'coordinator_email')
    # ### end Alembic commands ###
