/**
 * Passport API client and types.
 *
 * Import from `@lib/passport` rather than reaching into `./api` or
 * `./types` directly, so the module's surface is one org_unit and a later
 * reshuffle of the files inside it stays invisible to callers.
 */

export {
  PASSPORT_PATHS,
  acceptAssessorInvite,
  addCertificate,
  addCpdEntry,
  addLogbookEntry,
  addReflection,
  amendCertificate,
  certificateAttachmentUrl,
  amendCpdEntry,
  amendLogbookEntry,
  amendReflection,
  createPassport,
  declineSignOff,
  exportBundle,
  exportMarkdown,
  exportPdf,
  fetchCertificates,
  uploadEvidence,
  fetchAppraisalPeriods,
  fetchCpdYear,
  fetchInbox,
  fetchLogbook,
  fetchWholeLogbook,
  fetchMyPassport,
  fetchPassport,
  fetchPassportSpecialties,
  fetchReflections,
  fetchSignOff,
  fetchSignOffs,
  previewAssessorInvite,
  removeCertificate,
  removeCpdEntry,
  removeLogbookEntry,
  removeReflection,
  requestSignOff,
  searchAssessors,
  revokeAssessorMembership,
  saveAppraisalPeriods,
  setPassportSpecialties,
  signOff,
  verifySignOff,
  withdrawSignOff,
} from "./api";

export type {
  Assessor,
  AssessorInviteAccept,
  AssessorInviteAcceptInput,
  AssessorRevoke,
  Attachment,
  AttachmentInput,
  Certificate,
  CertificateInput,
  CompetencyRef,
  CompetencyState,
  CpdActivityType,
  CpdEntry,
  CpdEntryInput,
  EvidenceSnapshot,
  EvidenceUpload,
  InvitePreview,
  IsoDate,
  IsoDateTime,
  LevelRef,
  Logbook,
  WholeLogbook,
  LogbookEntry,
  LogbookEntryInput,
  Passport,
  PassportDetail,
  InboxItem,
  RecordResult,
  Reflection,
  ReflectionInput,
  Registration,
  SignOff,
  SignOffDeclineInput,
  SignOffInput,
  SignOffKind,
  SignOffMeaning,
  AssessorMatch,
  AssessorSearch,
  SignOffRequestInput,
  SignOffResult,
  SignOffStatus,
  Supervision,
  Verification,
  Specialty,
  SpecialtyChoice,
  AppraisalPeriod,
} from "./types";

export { PASSPORT_SPECIALTIES, getPassportSpecialty } from "./specialties";
export type { PassportSpecialtyDefinition } from "./specialties";
export { levelsFor } from "./levels";
export type { LevelOption } from "./levels";
export { registrationAuthorities } from "./registrationAuthorities";
export type { RegistrationAuthorityOption } from "./registrationAuthorities";
